micronaut:
  application:
    name: micronautKotlinMicroservice
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    endpoints:
      login:
        path: /auth/login

  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
vertx:
  pg:
    client:
      port: 5432
      host: the-host
      database: microservice
      user: postgres
      password: root
      maxSize: 5
r2dbc:
  datasources:
    default:

flyway:
  datasources: 
    default: 
      enabled: true
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres

endpoints:
  flyway:
    enabled: true 
    sensitive: false 
